# vim:ft=kitty

# text
dark_foreground           #cad3f5
# base
dark_background           #24273a

# subtext0
dark_title_fg             #a5adcb
# base
dark_title_bg             #24273a
# subtext1
dark_margin_fg            #b8c0e0
# mantle
dark_margin_bg            #1e2030

# base
dark_filler_bg            #24273a
dark_margin_filler_bg     #24273a

# 30% red, 70% base
dark_removed_bg           #614455
# 50% red, 50% base
dark_highlight_removed_bg #895768
# 40% red, 60% base
dark_removed_margin_bg    #754d5f

# 30% green, 70% base
dark_added_bg             #4b5d55
# 50% green, 50% base
dark_highlight_added_bg   #658068
# 40% green, 60% base
dark_added_margin_bg      #754d5f

# mantle
dark_hunk_margin_bg       #1e2030
dark_hunk_bg              #1e2030

# 40% yellow, 60% base
dark_search_bg            #756c63
# text
dark_search_fg            #cad3f5
# 30% sky, 70% base
dark_select_bg            #455c6d
# text
dark_select_fg            #cad3f5
