services:
  app:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:latest
    restart: unless-stopped
    ports:
      - 3474:80
    networks:
      - lan

networks:
  lan:
    name: lan
    external: true
