keys:
  - &eden age1cqn2lzacjwhtpecsnhjc2nf659va465sa2evdw37jahkg03jaavs2slpq0

  - &Newton age1llg9sg0w2xar2kp40ald5vl55e8yqtu9v4pe90xfl8qk2rd394msau8rt3
  - &Notebook age1hlcz002grl23atw676g9ruwld9jjkkr0jcgwvl7dfyt9y4nzp5sqxdg84z
  - &Orion age12gfgfuzwxd43p2uw0fuef2efhz6y4w8juz4d243uudzqa2pmhaqqkasrt3

creation_rules:
  - path_regex: secrets/eden\.yaml
    key_groups:
      - age:
          - *eden

  - path_regex: secrets/services/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *eden

          - *Newton
          - *Notebook
          - *Orion
