# Unbinds
unbind %
unbind '"'
unbind -n MouseDown3Pane
unbind -T copy-mode-vi MouseDragEnd1Pane

# Config reload
bind ! source-file ~/.config/tmux/tmux.conf \; display "   Reloaded "

# Lock
bind L lock
# bind L send-keys '^L'

# Status bar
bind * set -g status

# Copy mode
# bind v copy-mode
bind v run-shell ~/.config/tmux/scripts/copy-mode
bind -T copy-mode-vi v send-keys -X begin-pipe
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind p paste-buffer
# bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

# Search Text
bind / copy-mode \; send-keys /

# Layouts
bind -n M-v select-layout main-vertical
bind -n M-z select-layout main-horizontal
bind -n M-V select-layout even-vertical
bind -n M-Z select-layout even-horizontal

# New Session & Window
bind '$' command-prompt -p " new session ->" "run-shell 'tmux new-session -d -s %1 && tmux switch-client -t %1'" # New session
bind Enter new-window -c "#{pane_current_path}" # New window
bind -n M-t new-window
bind -n M-Enter new-window

# Change Session & Window name
bind R command-prompt -I "#{session_name}" "rename-session '%%'"
bind r command-prompt -I "#W" "rename-window '%%'"

# Pane resizing
bind -n C-left if -F "#{@pane-is-vim}" 'send-keys C-left' 'resize-pane -L 5'
bind -n C-down if -F "#{@pane-is-vim}" 'send-keys C-down' 'resize-pane -D 5'
bind -n C-up if -F "#{@pane-is-vim}" 'send-keys C-up' 'resize-pane -U 5'
bind -n C-right if -F "#{@pane-is-vim}" 'send-keys C-right' 'resize-pane -R 5'

# Swap Pane
bind > swap-pane -D
bind < swap-pane -U

# Zoom Pane
bind -n M-z resize-pane -Z

# Windows ls
# bind -n M-w choose-window
bind -n M-w run-shell "tmux choose-tree -Zw -f '##{==:##{session_name},#{session_name}}'"

# Move to Window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t:9
bind -n M-0 select-window -t:10

# Move to next & prev Window
bind -n C-p previous-window
bind -n C-n next-window

bind h previous-window
bind l next-window

# Split Window
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Swap Window
bind -n M-, swap-window -d -t -1
bind -n M-. swap-window -d -t +1

# Sessions ls
bind -n M-s choose-session

# Move to next & prev Session
bind j switch-client -n
bind k switch-client -p

# Detach Session
bind d confirm-before -p "detach session? " detach-client

# Kill Session, Window & Pane
bind Q confirm-before -p "Kill session? " kill-session
bind -n M-q kill-pane

# App Windows
bind b new-window -n btop "btop"
bind f new-window -n fzf -c "#{pane_current_path}" "fd -H -L --type f | fzf --preview 'bat --style=numbers --color=always --line-range :500 {}' | xargs -r nvim"
bind -n M-g new-window -n lazygit -c "#{pane_current_path}" "lazygit"
bind i command-prompt -p "open app: " "new-window '%%'"
bind o new-window -n A1 "opencode"
bind s new-window -n Sounds "~/.local/bin/sounds"
bind T new-window -n To-Do "nvim ~/Obsidian/To-do.md"
bind q new-window -n dash -c "#{pane_current_path}" "gh dash"
bind y new-window -n yazi -c "#{pane_current_path}" "yazi"

# Sessions
bind '#' popup -E -h 90% -w 100% "sessionizer"
bind D run-shell "~/.local/bin/sessions dotfiles"
bind M run-shell "~/.local/bin/sessions mail"
bind N run-shell "~/.local/bin/sessions feeds"
bind O run-shell "~/.local/bin/sessions notes"

# Floats
bind -n M-\\ run-shell "~/.config/tmux/scripts/term"
bind E display-popup -y 40 -w "99%" -h "99%" -b rounded -d "#{pane_current_path}" -E "fd --type f | fzf | xargs -r nvim"

# Help
bind C-g display-popup -y 40 -w "96%" -h "90%" -b rounded -d "#{pane_current_path}" -E \
  "$SHELL --login -i -c 'navi --print | tmux load-buffer -b tmp - ; tmux paste-buffer -p -t {last} -b tmp -d'"
