#!/usr/bin/env bash

uptime="$(uptime -p | sed -e 's/up //g')"
shutdown='󰐥'
reboot='󰜉'
lock=''
suspend='󰤄'
logout='󰍃'
yes='󰸞'
no='󱎘'

rofi_cmd() {
  rofi -dmenu \
    -p "Uptime: $uptime" \
    -mesg "Uptime: $uptime" \
    -theme "$HOME/.config/rofi/scripts/powermenu/style.rasi"
}

confirm_cmd() {
  rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
    -theme-str 'mainbox {children: [ "message", "listview" ];}' \
    -theme-str 'listview {columns: 2; lines: 1;}' \
    -theme-str 'element-text {horizontal-align: 0.5;}' \
    -theme-str 'textbox {horizontal-align: 0.5;}' \
    -dmenu \
    -p 'Confirmation' \
    -mesg 'Are you sure?' \
    -theme "$HOME/.config/rofi/scripts/powermenu/style.rasi"
}

confirm_exit() {
  echo -e "$yes\n$no" | confirm_cmd
}

run_rofi() {
  echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

run_cmd() {
  selected="$(confirm_exit)"
  if [[ "$selected" == "$yes" ]]; then
    if [[ $1 == '--shutdown' ]]; then
      systemctl poweroff
    elif [[ $1 == '--reboot' ]]; then
      systemctl reboot
    elif [[ $1 == '--suspend' ]]; then
      mpc -q pause
      systemctl hibernate
      if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then hyprlock; else swaylock; fi
    elif [[ $1 == '--logout' ]]; then
      if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then hyprctl dispatch exit; else swaymsg exit; fi
    elif [[ $1 == '--lock' ]]; then
      # pkill -f "kitty --class Screensaver"
      if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then hyprlock; else swaylock; fi
    fi
  else
    exit 0
  fi
}

chosen="$(run_rofi)"
case ${chosen} in
$shutdown)
  run_cmd --shutdown
  ;;
$reboot)
  run_cmd --reboot
  ;;
$lock)
  run_cmd --lock
  ;;
$suspend)
  run_cmd --suspend
  ;;
$logout)
  run_cmd --logout
  ;;
esac
