#!/usr/bin/env bash

TMP_FILE="$XDG_RUNTIME_DIR/hyprland-show-desktop"

CURRENT_WORKSPACE=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true) | .activeWorkspace.name')

if [ -s "$TMP_FILE-$CURRENT_WORKSPACE" ]; then
  readarray -d $'\n' -t ADDRESS_ARRAY <<<$(<"$TMP_FILE-$CURRENT_WORKSPACE")

  for address in "${ADDRESS_ARRAY[@]}"; do
    if [[ -n "$address" ]]; then
      CMDS+="dispatch hl.dsp.window.move({workspace='$CURRENT_WORKSPACE', follow=false, window='address:$address'}) ; "
    fi
  done

  if [[ -n "$CMDS" ]]; then
    hyprctl --batch "${CMDS% ; }"
  fi

  rm "$TMP_FILE-$CURRENT_WORKSPACE"
else
  HIDDEN_WINDOWS=$(hyprctl clients -j | jq -r --arg CW "$CURRENT_WORKSPACE" '.[] | select (.workspace.name == $CW) | .address')

  readarray -d $'\n' -t ADDRESS_ARRAY <<<"$HIDDEN_WINDOWS"

  for address in "${ADDRESS_ARRAY[@]}"; do
    if [[ -n "$address" ]]; then
      TMP_ADDRESS+="$address\n"
      CMDS+="dispatch hl.dsp.window.move({workspace='special:desktop', follow=false, window='address:$address'}) ; "
    fi
  done

  if [[ -n "$CMDS" ]]; then
    hyprctl --batch "${CMDS% ; }"
    echo -e "$TMP_ADDRESS" | sed -e '/^$/d' >"$TMP_FILE-$CURRENT_WORKSPACE"
  fi
fi
