#!/usr/bin/env bash

workspace_id=$(hyprctl activeworkspace -j | jq -r .id)
gaps=$(hyprctl workspacerules -j | jq -r ".[] | select(.workspaceString==\"$workspace_id\") | .gapsOut[0] // 0")

if [[ $gaps == "0" ]]; then
  hyprctl eval "hl.workspace_rule({ workspace = \"$workspace_id\", gaps_out = 10, gaps_in = 4, no_rounding = false, border_size = 2 })"
else
  hyprctl eval "hl.workspace_rule({ workspace = \"$workspace_id\", gaps_out = 0, gaps_in = 0, no_rounding = true, border_size = 0 })"
fi
