#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Videos/Wallpapers"
MPV_OPTIONS="no-audio loop --no-resume-playback vo=libmpv gpu-api=vulkan hwdec=nvdec vd-lavc-threads=$(nproc) vf=fps=30"

DIRECT_PATH=""
VIDEO_TO_PLAY=""

while getopts "hp:" opt; do
  case $opt in
  p)
    DIRECT_PATH="$OPTARG"
    ;;
  h)
    echo "Usage: $0 [-p <path>]"
    echo "Options:"
    echo "  -p <path>           Set wallpaper from a direct path."
    exit 0
    ;;
  \?)
    echo "Usage: $0 [-p <path>]" >&2
    exit 1
    ;;
  esac
done
shift $((OPTIND - 1))

if [ -n "$DIRECT_PATH" ]; then
  VIDEO_TO_PLAY="$DIRECT_PATH"
else
  VIDEO_FILES=()
  while IFS= read -r file; do
    VIDEO_FILES+=("$file")
  done < <(find "$WALLPAPER_DIR" -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.webm" -o -name "*.avi" -o -name "*.mov" \))

  if [ ${#VIDEO_FILES[@]} -eq 0 ]; then
    echo "No video files found in $WALLPAPER_DIR"
    exit 1
  fi
  VIDEO_TO_PLAY="${VIDEO_FILES[RANDOM % ${#VIDEO_FILES[@]}]}"
fi

mpvpaper -l overlay -o "$MPV_OPTIONS" '*' "$VIDEO_TO_PLAY" &
MPVPAPER_PID=$!

sleep 0.5

hyprlock

kill "$MPVPAPER_PID"
