#!/usr/bin/env bash

if pgrep -f "gpu-screen-recorder" >/dev/null; then
  pkill -INT -f gpu-screen-recorder
  notify-send -u normal -t "$NOTIF_TIMEOUT" "Previous recording stopped" "Recording exited."
  exit 0
fi

set -e

DEFAULT_OUTPUT_DIR="$HOME/Videos/Screen Recording"
DELAY=0
SILENT=0
NOTIF_TIMEOUT=5000
DATE_TIME_FORMAT="+%Y-%m-%d_%H-%M-%S"
OUTPUT_FILE_EXTENSION=".mkv"
CUSTOM_FILENAME=""
RECORD_MIC=0

Help() {
  cat <<EOF
Usage: screenrcd [options]

eg:
  Record fullscreen:                        screenrcd
  Record with 5s delay:                     screenrcd --delay 5
  Record to custom dir:                     screenrcd --output-folder ~/MyRecordings

Options:
  -h, --help                                Show help msg.
  -o, --output-folder <dir>                 Save Directory [default: $DEFAULT_OUTPUT_DIR].
  -f, --filename <name>                     Custom filename [default: YYYY-MM-DD_HH-MM-SS.mkv].
  -D, --delay <seconds>                     Countdown Delay [default: $DELAY].
  -s, --silent                              Silent notify.
  -t, --notif-timeout <ms>                  Notification timeout in milliseconds [default: $NOTIF_TIMEOUT].
  -a, --audio                               Record microphone audio.

EOF
}

send_notification() {
  if [ "$SILENT" -eq 1 ]; then
    return 0
  fi

  local output_file="$1"
  local message="Recording Captured"$'\n'"$(echo "Video saved in $output_file" | fold -s -w 70)"

  local action
  action=$(notify-send -i "video-x-generic" -u normal -a "Screen Recorder" "$message" \
    --action="view=View File" \
    --action="folder=Open Folder" \
    -t "$NOTIF_TIMEOUT")

  case "$action" in
  "view")
    mpv --hwdec=nvdec "$output_file"
    ;;
  "folder")
    xdg-open "$(dirname "$output_file")"
    ;;
  *)
    echo "No valid action selected or notification dismissed."
    ;;
  esac
}

run_fullscreen_record() {
  local current_output_file="$1"
  local audio_args="-a default_output"

  if [ "$RECORD_MIC" -eq 1 ]; then
    audio_args="-a 'default_output|default_input'"
  fi

  for i in {3..1}; do
    notify-send -e \
      -h string:x-canonical-private-synchronous:record_countdown \
      -h int:value:$i \
      -i "computer" \
      "Recording in:" "<span color='#90a4f4' font='26px'><i><b>$i</b></i></span>"
    if pgrep -f "gpu-screen-recorder" >/dev/null; then
      notify-send -u normal -t "$NOTIF_TIMEOUT" "Recording exited" "Stopped before starting."
      exit 0
    fi
    sleep 1
  done

  notify-send -e \
    -h string:x-canonical-private-synchronous:record_countdown \
    -h int:value:0 \
    -i "computer" \
    -t 1 "" ""

  [ "$DELAY" -gt 0 ] && sleep "$DELAY"

  eval gpu-screen-recorder -w screen $audio_args -v no -s 1920x1080 -k hevc -q very_high -cr full -o \"$current_output_file\" || {
    notify-send -u critical -t "Recording failed!" "There was an error starting the recording."
    exit 1
  }

  send_notification "$current_output_file"
}

args() {
  local options=$(getopt -o hf:o:D:sta --long help,output-folder:,filename:,delay:,silent,notif-timeout:,audio -- "$@")
  eval set -- "$options"

  while true; do
    case "$1" in
    -h | --help)
      Help
      exit 0
      ;;
    -o | --output-folder)
      shift
      OUTPUT_DIR="$1"
      ;;
    -f | --filename)
      shift
      FILENAME="$1"
      CUSTOM_FILENAME=1
      ;;
    -D | --delay)
      shift
      DELAY="$1"
      ;;
    -s | --silent) SILENT=1 ;;
    -t | --notif-timeout)
      shift
      NOTIF_TIMEOUT="$1"
      ;;
    -a | --audio) RECORD_MIC=1 ;;
    --)
      shift
      break
      ;;
    *)
      echo "Internal error: unrecognized option '$1'" >&2
      exit 1
      ;;
    esac
    shift
  done
}

OUTPUT_DIR="${OUTPUT_DIR:-$DEFAULT_OUTPUT_DIR}"
[ -z "$CUSTOM_FILENAME" ] && FILENAME="$(date "$DATE_TIME_FORMAT")$OUTPUT_FILE_EXTENSION"

args "$@"
mkdir -p "$OUTPUT_DIR"
FULL_OUTPUT_FILE="$OUTPUT_DIR/$FILENAME"

run_fullscreen_record "$FULL_OUTPUT_FILE"
