#!/usr/bin/env bash

is_floating=$(hyprctl activewindow -j | jq -r '.floating')

if [ "$is_floating" = "true" ]; then
  hyprctl dispatch 'hl.dsp.focus({window="tiled"})'
else
  hyprctl dispatch 'hl.dsp.focus({window="floating"})'
fi
