#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Developer/Wallpapers"
random=$(fd --base-directory "$WALLPAPER_DIR" --type f . | shuf -n 1)

WALLPAPER="$WALLPAPER_DIR/$random"
SYMLINK_PATH="$HOME/.config/hypr/lock"

if pgrep -x "hyprpaper" >/dev/null; then
  hyprctl hyprpaper wallpaper ",$WALLPAPER"
elif pgrep -x "swww" >/dev/null; then
  swww img "$WALLPAPER" \
    --transition-bezier 0.5,1.19,.8,.4 \
    --transition-type wipe \
    --transition-duration 2 \
    --transition-fps 30
fi

ln -sf "$WALLPAPER" "$SYMLINK_PATH"
