{
  imports = [
    ./pkgs.nix

    ./aerospace.nix
    ./aria2.nix
    ./atuin.nix
    ./bat.nix
    ./batsignal.nix
    ./btop.nix
    ./caffeine.nix
    ./cava.nix
    ./chromium.nix
    ./clipse.nix
    ./cursors.nix
    ./direnv.nix
    ./discord.nix
    ./editorconfig.nix
    ./espanso.nix
    ./eviv2-thumbnailer.nix
    ./eza.nix
    ./fastfetch.nix
    ./fd.nix
    ./firefox.nix
    ./fonts.nix
    ./foot.nix
    ./fzf.nix
    ./gallery-dl.nix
    ./gcc.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./glab.nix
    ./glow.nix
    ./gtk.nix
    ./hypr
    ./hx.nix
    ./jelly.nix
    ./jj.nix
    ./jrnl.nix
    # ./keepassxc.nix
    ./kitty.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./lazysql.nix
    ./mako.nix
    ./man.nix
    ./mangohud.nix
    ./macos-terminal.nix
    ./mise.nix
    ./mpd.nix
    ./mpv.nix
    ./mpvpaper.nix
    ./neomutt.nix
    ./nix-your-shell.nix
    ./nixvim
    ./npm.nix
    ./nvibrant.nix
    ./obs.nix
    ./ollama.nix
    ./oh-my-posh.nix
    ./opencode.nix
    ./pass.nix
    ./pi.nix
    ./posting.nix
    # ./qt.nix
    ./qutebrowser.nix
    ./rg.nix
    ./rmpc.nix
    ./rnnoise.nix
    ./rofi.nix
    ./satty.nix
    ./screen.nix
    ./shell
    ./sops.nix
    ./spotify.nix
    ./ssh.nix
    ./starship.nix
    ./steam.nix
    ./superfile.nix
    ./sway
    ./swayimg.nix
    ./swaync.nix
    ./syncthing.nix
    ./theme.nix
    ./thunderbird.nix
    ./tmux.nix
    ./tt.nix
    ./udiskie.nix
    ./vim.nix
    ./vivid.nix
    ./w3m.nix
    ./wiremix.nix
    ./wlsunset.nix
    ./wob.nix
    ./yazi.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zed.nix
    ./zen.nix
    ./zoxide.nix
  ];
}
