# Theme
color_scheme dark
include themes/diff-macchiato.conf

## Keybinds

# Quit
map q quit
map esc quit

# Scroll down
map j scroll_by 1
map down scroll_by 1

# Scroll up
map k scroll_by -1
map up scroll_by -1

# Scroll to top
map home scroll_to start

# Scroll to bottom
map end scroll_to end

# Scroll to next page
map page_down scroll_to next-page
map space scroll_to next-page
map ctrl+f scroll_to next-page

# Scroll to previous page
map page_up scroll_to prev-page
map ctrl+b scroll_to prev-page

# Scroll down half page
map ctrl+d scroll_to next-half-page

# Scroll up half page
map ctrl+u scroll_to prev-half-page

# Scroll to next change
map n scroll_to next-change

# Scroll to previous change
map p scroll_to prev-change

# Scroll to next file
map shift+j scroll_to next-file

# Scroll to previous file
map shift+k scroll_to prev-file

# Show all context
map a change_context all

# Show default context
map = change_context default

# Increase context
map + change_context 5

# Decrease context
map - change_context -5

# Search forward
map / start_search regex forward

# Search backward
map ? start_search regex backward

# Scroll to next search match
map . scroll_to next-match
map > scroll_to next-match

# Scroll to previous search match
map , scroll_to prev-match
map < scroll_to prev-match

# Search forward (no regex)
map f start_search substring forward

# Search backward (no regex)
map b start_search substring backward

# Copy selection to clipboard
map y copy_to_clipboard

# Copy selection to clipboard or exit if no selection is present
map ctrl+c copy_to_clipboard_or_exit
