# https://github.com/Samillion/ModernZ/tree/cd23007c69f1f7d82a80b9369e9ab974abb82837

# show download button on web videos (requires yt-dlp and ffmpeg)
download_path=~~Videos/mpv

# show window controls (close, minimize, maximize) in borderless/fullscreen
window_controls=no
# show file loop button
loop_button=no
# show speed control button
speed_button=no
# show the audio tracks menu button
audio_tracks_button=no
# show mute button and volume slider
volume_control=no
# show playlist button
playlist_button=no
# show window on top button
ontop_button=no
# show fullscreen toggle button
fullscreen_button=no
# show window on top button
info_button=no
# show screenshot button
screenshot_button=no

# Colors and style
# accent color of the OSC and title bar
osc_color=#24273A
# color of the title
title_color=#B7BDF8
# color of the cache information
cache_info_color=#CAD3F5
# color of the cache ranges on the seekbar
seekbar_cache_color=#6E738D
# color of the seekbar progress
seekbarfg_color=#8AADF4
# color of the remaining seekbar
seekbarbg_color=#B7BDF8
# color of the seekbar handle
seek_handle_color=#eed49f
# inner border color drawn inside the seekbar handle (set to disable to disable)
seek_handle_border_color=#f4dbd6
# color of the timestamps (below seekbar)
time_color=#CAD3F5
# color of the chapter title
chapter_title_color=#CAD3F5
# color of the side buttons (audio, subtitles, playlist, etc.)
side_buttons_color=#CAD3F5
# color of the middle buttons (skip, jump, chapter, etc.)
middle_buttons_color=#CAD3F5
# color of the play/pause button
playpause_color=#CAD3F5
# color of the element when held down (pressed)
held_element_color=#6E738D
# color of a hovered button when hover_effect includes "color"
hover_effect_color=#8AADF4
# color of the background for thumbnail box
thumbnail_box_color=#24273A
# color of the border outline for thumbnail box
thumbnail_box_outline=#24273A

# Button hover effects
# active button hover effects: "glow", "size", "color"; can use multiple separated by commas
hover_effect=size,color

