#!/usr/bin/env bash

declare -r LINE_NUMBER_PANE_WIDTH=3
declare -r LINE_NUMBER_UPDATE_DELAY=0.1
declare -r COLOR_NUMBERS_RGB="110;115;141"
declare -r COLOR_ACTIVE_NUMBER_RGB="198;160;246"

open_line_number_split() {
  local self_path=$(realpath $0)
  local pane_id=$(tmux display-message -pF "#{pane_id}")

  if pgrep -f "$self_path $pane_id" >/dev/null; then
    return
  fi

  tmux split-window -h -l $LINE_NUMBER_PANE_WIDTH -b "$self_path $pane_id"
  tmux select-pane -l
}

enter_copy_mode() {
  local target_pane=$1
  tmux copy-mode -t "$target_pane"
}

get_cursor_line() {
  local output=$(tmux display-message -pt "$target_pane" -F '#{copy_cursor_y}')
  echo "${output:-0}"
}

get_absolute_line() {
  local target_pane=$1
  local cursor_y=$(tmux display-message -pt "$target_pane" -F '#{copy_cursor_y}')
  local scroll_pos=$(tmux display-message -pt "$target_pane" -F '#{scroll_position}')
  local history_size=$(tmux display-message -pt "$target_pane" -F '#{history_size}')

  echo $((history_size - scroll_pos + cursor_y + 1))
}

is_in_copy_mode() {
  local mode=$(tmux display-message -p -t "$target_pane" -F '#{pane_mode}')
  ! [ -z $mode ]
}

redraw_line_numbers() {
  local cursor_line=$1
  local absolute_line=$2
  local lines=$(tput lines)

  clear

  printf "\e[38;2;$COLOR_NUMBERS_RGB;2m"
  for i in $(seq $cursor_line -1 1); do
    printf "%-3d\n" $i
  done
  printf "\e[0m"

  printf "\e[38;2;$COLOR_ACTIVE_NUMBER_RGB;1m%-3d\e[0m" $absolute_line

  if [ $lines -gt $(($cursor_line + 1)) ]; then
    echo
    printf "\e[38;2;$COLOR_NUMBERS_RGB;2m"
    for i in $(seq 1 $(($lines - $cursor_line - 2))); do
      printf "%-3d\n" $i
    done
    printf "%-3d" $((lines - $cursor_line - 1))
    printf "\e[0m"
  fi
}

update_loop() {
  local cursor_line=""
  local last_cursor_line="-1"
  local absolute_line=""
  local last_absolute_line="-1"

  while is_in_copy_mode; do
    cursor_line=$(get_cursor_line)
    absolute_line=$(get_absolute_line "$target_pane")

    if [ $cursor_line -ne $last_cursor_line ] || [ $absolute_line -ne $last_absolute_line ]; then
      redraw_line_numbers $cursor_line $absolute_line
      last_cursor_line=$cursor_line
      last_absolute_line=$absolute_line
    fi

    sleep $LINE_NUMBER_UPDATE_DELAY
  done
}

restore_pane_width() {
  local target_pane=$1
  tmux resize-pane -t "$target_pane" -L $(($LINE_NUMBER_PANE_WIDTH + 1))
}

main() {
  local target_pane=$1

  if [ -z $target_pane ]; then
    open_line_number_split
    exit 0
  else
    enter_copy_mode $target_pane
  fi

  update_loop
  restore_pane_width $target_pane
}

main "$@"
