# █   ▄▀█ █ █ █▄ █ █▀▀ █ █
# █▄▄ █▀█ █▄█ █ ▀█ █▄▄ █▀█

# Apps
set $launcher rofi -show drun

set $notifications-menu makoctl
set $notifications-menu-read    $notifications-menu dismiss -a
set $notifications-menu-dnd     $notifications-menu mode -t do-not-disturb
set $notifications-menu-reload  $notifications-menu reload

set $browser          qutebrowser
set $browser-ALT      firefox
set $editor $term-ALT nvim
set $editor-gui       zeditor
set $file-manager     yazi
set $file-manager-gui nautilus --new-window
set $mail             thunderbird
set $notes            obsidian -disable-gpu
set $term             footclient
set $term-ALT         kitty --single-instance
set $term-tmp         kitty --single-instance -o close_on_child_death=yes -e zsh -ic
set $webapp           $browser-ALT --private-window