# █▀▄▀█ █▀█ █▄ █ █ ▀█▀ █▀█ █▀█ █▀
# █ ▀ █ █▄█ █ ▀█ █  █  █▄█ █▀▄ ▄█

output eDP-1 {
  mode 1920x1080@60.052Hz
  pos 0 0
  transform normal
  scale 1.5
  scale_filter nearest
  adaptive_sync off
  allow_tearing yes
  max_render_time off
  dpms on
  bg #24273a solid_color
  # bg ~/Developer/Wallpapers/Nix 1.png fill
}

output DP-1 {
  mode 1920x1080@60.052Hz
  pos 0 1080
  scale 1.5
  scale_filter nearest
  adaptive_sync off
  allow_tearing yes
  adaptive_sync off
  color_profile srgb
  max_render_time off
  dpms on
  bg #24273a solid_color
  # bg ~/Developer/Wallpapers/architecture.jpg fill
}

# exec ~/.config/sway/scripts/wallpaper &