# █▀ █ █ █ ▄▀█ █▄█ █ █▀▄ █   █▀▀
# ▄█ ▀▄▀▄▀ █▀█  █  █ █▄▀ █▄▄ ██▄

set $lock 300
set $sleep 400
set $suspend 404

exec swayidle -w \
  timeout "$lock" 'swaylock -f' \
  timeout "$sleep" 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
  timeout "$suspend" 'systemctl hibernate' \
  before-sleep 'playerctl pause; swaylock -f'