bar {
  position top
  font pango: JetBrainsMono Nerd Font 12.4
  separator_symbol "|"
  # status_command while date +'󰥔 %H:%M '; do sleep 1; done
  status_command while true; do ~/.config/sway/scripts/swaybar; sleep 1; done
  pango_markup enabled

  colors {
    statusline #CAD3F5
    background #24273A
    separator #CAD3F5

    focused_workspace #B7BDF8 #B7BDF8 #24273A
    active_workspace #363A4F #24273A #CAD3F5
    inactive_workspace #24273A #24273A #CAD3F5
    urgent_workspace #ED8796 #ED8796 #CAD3F5
    binding_mode #ED8796 #ED8796 #CAD3F5
  }
}
