# █ █ █ █▀█ █▀█ █▄▀ █▀ █▀█ ▄▀█ █▀▀ █▀▀ █▀
# ▀▄▀▄▀ █▄█ █▀▄ █ █ ▄█ █▀▀ █▀█ █▄▄ ██▄ ▄█

workspace 1  output eDP-1
workspace 2  output eDP-1
workspace 3  output eDP-1
workspace 4  output eDP-1
workspace 5  output eDP-1
workspace 6  output eDP-1
workspace 7  output eDP-1
workspace 8  output eDP-1
workspace 9  output eDP-1
workspace 10 output eDP-1

workspace 5 gaps inner 4
workspace 5 gaps horizontal 20
workspace 5 gaps vertical 20

workspace 10 gaps inner 4
workspace 10 gaps horizontal 20
workspace 10 gaps vertical 20

workspace 11 output DP-1
workspace 12 output DP-1
workspace 13 output DP-1
workspace 14 output DP-1
workspace 15 output DP-1
workspace 16 output DP-1
workspace 17 output DP-1
workspace 18 output DP-1
workspace 19 output DP-1
workspace 20 output DP-1

workspace 15 gaps inner 6
workspace 15 gaps horizontal 40
workspace 15 gaps vertical 40

workspace 20 gaps inner 6
workspace 20 gaps horizontal 40
workspace 20 gaps vertical 40

# exec sleep 0.5 && ~/.config/sway/scripts/workspaces