#!/usr/bin/env bash

# ▄▀█ █▀█ █▀█ █▀
# █▀█ █▀▀ █▀▀ ▄█

# Apps
# thunderbird &
# obsidian -disable-gpu &

# Term Apps
# kitty --class btop btop &
# kitty --class nvitop nvitop &
# ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false &
