#!/usr/bin/env bash

# █▀▀ ▀▄▀ █▀▀ █▀▀  █▀ █▀▀ █▀█ █ █ █ █▀▀ █▀▀ █▀
# ██▄ █ █ ██▄ █▄▄  ▄█ ██▄ █▀▄ ▀▄▀ █ █▄▄ ██▄ ▄█

# xwayland
# xwayland-satellite &

# Display
brightnessctl s 1067 &

# Notify connecting & disconnecting devices
# devify &

# Clipboard
rm "$HOME/.cache/cliphist/db" &