#!/usr/bin/env bash

name=$1
shift
cmd="$*"

if swaymsg -t get_tree | jq -e '.. | select(.app_id?=="'$name'" and .scratchpad_state?=="fresh")' >/dev/null; then
  swaymsg "[app_id=\"$name\"] opacity set 0, scratchpad show"
  sleep 0.1
  swaymsg "[app_id=\"$name\"] move position center, opacity set 1"
else
  swaymsg '[floating title="^(?!Picture-in-Picture$).*"] move scratchpad' 2>/dev/null

  if swaymsg -t get_tree | grep -qP "\"app_id\":\s*\"${name}\""; then
    swaymsg "[app_id=\"$name\"] opacity set 0, scratchpad show"
    sleep 0.1
    swaymsg "[app_id=\"$name\"] move position center, opacity set 1"
  else
    first_word=$(echo $cmd | awk '{print $1}')
    rest=$(echo $cmd | cut -d' ' -f2-)
    if [ "$rest" = "$first_word" ]; then
      $first_word --app-id="$name" &
    else
      $first_word --app-id="$name" $rest &
    fi

    sleep 0.4
    swaymsg "[app_id=\"$name\"] opacity set 0, scratchpad show"
    sleep 0.1
    swaymsg "[app_id=\"$name\"] move position center, opacity set 1"
  fi
fi
