#!/usr/bin/env bash

name=$1
shift
cmd="$*"

if swaymsg -t get_tree | jq -e '.. | select(.app_id?=="'$name'" and .scratchpad_state?=="fresh")' >/dev/null; then
  swaymsg "[app_id=\"$name\"] scratchpad show, move position center, border pixel 2"
else
  swaymsg "[floating] move scratchpad" 2>/dev/null

  if swaymsg -t get_tree | grep -qP "\"app_id\":\s*\"${name}\""; then
    swaymsg "[app_id=\"$name\"] move scratchpad, scratchpad show, move position center, border pixel 2"
  else
    first_word=$(echo $cmd | awk '{print $1}')
    rest=$(echo $cmd | cut -d' ' -f2-)
    if [ "$rest" = "$first_word" ]; then
      $first_word --class="$name" &
    else
      $first_word --class="$name" $rest &
    fi

    sleep 0.5
    swaymsg "[app_id=\"$name\"] move scratchpad, scratchpad show, move position center, border pixel 2"
  fi
fi
