# █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄ █ █▀
# █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█  █  █ █▄█ █ ▀█ ▄█

font pango: JetBrainsMono Nerd Font 12

gaps inner 0
gaps outer 0

gaps horizontal 0
gaps vertical   0

smart_gaps    off
smart_borders off

default_border pixel 2
default_floating_border pixel 2

title_align center
titlebar_padding 8 4
titlebar_border_thickness 2

default_orientation horizontal
floating_modifier $meta normal
focus_on_window_activation focus
# hide_edge_borders smart
popup_during_fullscreen smart

# Cursor
focus_wrapping no
seat * hide_cursor 5000
